coverage:
  status:
    project:
      default:
        target: 20%
        threshold: 0%
        paths:
          - "app/"
    patch:
      default:
        target: 0%
        threshold: 0%

comment:
  require_changes: true